### ISSUE TITLE
Warning+Error thrown by oneAPI, use of "arguments" must be qualified

### ISSUE THREAD

**Issue by cameton** [JuliaGPU/oneAPI.jl#127]
Trying to test out oneAPI.jl, package seems to throw an error due to a naming conflict with LLVM? The same error is thrown trying to run the kernel example from [this](https://juliagpu.org/post/2020-11-05-oneapi_0.1/) blogpost.

This is on Kubuntu 20.04 Linux.

```
julia> using oneAPI

julia> oneAPI.versioninfo()
Binary dependencies:
- NEO_jll: 21.31.20514+0
- libigc_jll: 1.0.8173+0
- gmmlib_jll: 21.2.1+0
- SPIRV_LLVM_Translator_jll: 11.0.0+2
- SPIRV_Tools_jll: 2021.2.0+0

Toolchain:
- Julia: 1.6.0
- LLVM: 11.0.1

1 driver:
- 00000000-0000-0000-16b8-d0b101010000 (v1.1.0, API v1.1.0)

1 device:
- Intel(R) UHD Graphics 620 [0x3ea0]


julia> function my_copy_transpose(dst, src, newaxes)
              i = get_global_id()
              idx_src = CartesianIndices(src)[i]
              idx_dest = CartesianIndex((idx_src[i] for i in newaxes)...)
              dst[idx_dest] = src[idx_src]
              return nothing
              end
my_copy_transpose (generic function with 1 method)

julia> src = oneArray(rand(2, 2, 2, 2, 2));

julia> dst = similar(src);

julia> @oneapi items=(2 ^ 5) my_copy_transpose(dst, src, (2, 1, 3, 4, 5))
WARNING: both oneL0 and LLVM export "arguments"; uses of it in module oneAPI must be qualified
ERROR: UndefVarError: arguments not defined
Stacktrace:
 [1] onecall(::oneAPI.oneL0.ZeKernel, ::Type, ::oneDeviceArray{Float64, 5, 1}, ::Vararg{Any, N} where N; groups::Int64, items::Int64, queue::oneAPI.oneL0.ZeCommandQueue)
   @ oneAPI ~/.julia/packages/oneAPI/PolvD/src/compiler/execution.jl:169
 [2] macro expansion
   @ ~/.julia/packages/oneAPI/PolvD/src/compiler/execution.jl:121 [inlined]                                                         
 [3] call(::oneAPI.HostKernel{my_copy_transpose, Tuple{oneDeviceArray{Float64, 5, 1}, oneDeviceArray{Float64, 5, 1}, Int64, Int64}}, ::oneDeviceArray{Float64, 5, 1}, ::oneDeviceArray{Float64, 5, 1}, ::Int64, ::Int64; call_kwargs::Base.Iterators.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:items,), Tuple{Int64}}})
   @ oneAPI ~/.julia/packages/oneAPI/PolvD/src/compiler/execution.jl:93
 [4] (::oneAPI.HostKernel{my_copy_transpose, Tuple{oneDeviceArray{Float64, 5, 1}, oneDeviceArray{Float64, 5, 1}, Int64, Int64}})(::oneArray{Float64, 5}, ::Vararg{Any, N} where N; kwargs::Base.Iterators.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:items,), Tuple{Int64}}})
   @ oneAPI ~/.julia/packages/oneAPI/PolvD/src/compiler/execution.jl:179
 [5] top-level scope
   @ ~/.julia/packages/oneAPI/PolvD/src/compiler/execution.jl:53
```

**Comment by maleadt** [comment]
You should always consider the `master` version of a package if you run into an issue. This has been fixed: 66cf7b1cc783a0a722fc7420ab5049d7789ce0fc.

**Comment by cameton** [comment]
Good to know, thanks! Should that be added to the README? Since the version that was added today by "] add oneAPI" seems to still have the issue.

**Comment by maleadt** [comment]
I don't think this should be added to the README specifically, it's a fairly generic Julia package recommendation. I'll look into releasing a new version so that it works out of the box again.
